const ADD_TODO = "ADD_TODO";
const DELETE_TODO = "DELETE_TODO";
const TOGGLE_TODO = "TOGGLE_TODO";
const ALL_DELETE_TODO = "ALL_DELETE_TODO";

export { 
    ADD_TODO, 
    DELETE_TODO, 
    TOGGLE_TODO,
    ALL_DELETE_TODO 
};
