const ADD_TODO = "ADD_TODO";
const DELETE_TODO = "DELETE_TODO";
const TOGGLE_TODO = "TOGGLE_TODO";
const REMOVE_COMPLETED_TODOS = "REMOVE_COMPLETED_TODOS"

export { 
    ADD_TODO, 
    DELETE_TODO, 
    TOGGLE_TODO,
    REMOVE_COMPLETED_TODOS
};
